#
# Module manifest for module 'FirewallRulesMigration'
#
# Generated by: t-kehui
#
# Generated on: 7/9/2019 1:31:54 PM
#

@{

# Script module or binary module file associated with this manifest.
RootModule = 'Intune-FWRules-Migration.psm1'

# Version number of this module.
ModuleVersion = '0.1'

# ID used to uniquely identify this module
GUID = '3f3a41b2-6dc6-463e-ac9e-1d7e1b7f4553'

# Author of this module
Author = 'Nick Benton, Kevin Hui and Tessy Emadoye'

# Company or vendor of this module
CompanyName = 'MEM v ENNBEE'

# Copyright statement for this module
Copyright = '(c) 2024 MEM v ENNBEE. All rights reserved.'

# Description of the functionality provided by this module
Description = 'PowerShell cmdlet suite to support automation of migrating Windows firewall rules to Microsoft Intune using new authentication method and rule profiles.'

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @("Microsoft.Graph", "ImportExcel")

# Assemblies that must be loaded prior to importing this module
# RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module.
# ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
# TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
# FormatsToProcess = @()

# Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
# NestedModules = @()

# Functions to export from this module
# FunctionsToExport = 'Get-Function'

# Cmdlets to export from this module
CmdletsToExport = @('Get-SampleFirewallData','Export-NetFirewallRule', 'Send-IntuneFirewallRulesPolicy', 'ConvertTo-IntuneFirewallRule', 'New-IntuneFirewallRule')

# Variables to export from this module
# VariablesToExport = '*'

# Aliases to export from this module
# AliasesToExport = ''

# List of all modules packaged with this module
# ModuleList = @()

# List of all files packaged with this module
# FileList = @()

# Private data to pass to the module specified in RootModule/ModuleToProcess
# PrivateData = ''

# HelpInfo URI of this module
# HelpInfoURI = ''

# Default prefix for commands exported from this module. Override the default prefix using Import-Module -Prefix.
# DefaultCommandPrefix = ''

}